JAVAC = javac
JRE = java
.PHONY: default clean
default: all ;
all: OthelloMove.class OthelloPlayer.class OthelloRandomPlayer.class OthelloState.class node.class OthelloMinMaxTushar.class OthelloAlphaBetaTushar.class OthelloTournamentTushar.class MonteCarloTushar.class MoteCarloTusharTime.class HW5.class
OthelloMove.class: OthelloMove.java
	$(JAVAC) OthelloMove.java
OthelloPlayer.class: OthelloPlayer.java
	$(JAVAC) OthelloPlayer.java
OthelloRandomPlayer.class: OthelloRandomPlayer.java
	$(JAVAC) OthelloRandomPlayer.java
OthelloState.class: OthelloState.java
	$(JAVAC) OthelloState.java
node.class: node.java
	$(JAVAC) node.java
OthelloMinMaxTushar.class: OthelloMinMaxTushar.java
	$(JAVAC) OthelloMinMaxTushar.java
OthelloAlphaBetaTushar.class: OthelloAlphaBetaTushar.java
	$(JAVAC) OthelloAlphaBetaTushar.java
OthelloTournamentTushar.class: OthelloTournamentTushar.java
	$(JAVAC) OthelloTournamentTushar.java
MonteCarloTushar.class: MonteCarloTushar.java
	$(JAVAC) MonteCarloTushar.java
MoteCarloTusharTime.class: MoteCarloTusharTime.java
	$(JAVAC) MoteCarloTusharTime.java
HW5.class: HW5.java
	$(JAVAC) HW5.java
clean:
	rm HW5.class OthelloTournamentTushar.class OthelloState.class OthelloAlphaBetaTushar.class OthelloMinMaxTushar.class OthelloRandomPlayer.class OthelloPlayer.class OthelloMove.class